title: Beneficiary Reporting API Documentation
baseurl: "/beneficiary-reporting-docs"
encoding: utf-8
sass:
  sass_dir: _sass
collections_dir: content
collections:
  topics:
    output: true
    permalink: /:collection/:path
  guides:
    output: true
    permalink: /:collection/:path
  references:
    output: true
    permalink: /:collection/:path
defaults:
  - scope:
      path: ""
      type: topics
    values:
      layout: page
  - scope:
      path: ""
      type: guides
    values:
      layout: page
  - scope:
      path: ""
      type: references
    values:
      layout: page
